// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: api-gateway.proto

/*
Package api_gateway is a generated protocol buffer package.

It is generated from these files:
	api-gateway.proto

It has these top-level messages:
*/
package api_gateway

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import go_api "github.com/micro/go-api/proto"

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = go_api.Response{}

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Gateway service

type GatewayService interface {
	Call(ctx context.Context, in *go_api.Request, opts ...client.CallOption) (*go_api.Response, error)
	Login(ctx context.Context, in *go_api.Request, opts ...client.CallOption) (*go_api.Response, error)
}

type gatewayService struct {
	c    client.Client
	name string
}

func NewGatewayService(name string, c client.Client) GatewayService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "gateway"
	}
	return &gatewayService{
		c:    c,
		name: name,
	}
}

func (c *gatewayService) Call(ctx context.Context, in *go_api.Request, opts ...client.CallOption) (*go_api.Response, error) {
	req := c.c.NewRequest(c.name, "Gateway.Call", in)
	out := new(go_api.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayService) Login(ctx context.Context, in *go_api.Request, opts ...client.CallOption) (*go_api.Response, error) {
	req := c.c.NewRequest(c.name, "Gateway.Login", in)
	out := new(go_api.Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Gateway service

type GatewayHandler interface {
	Call(context.Context, *go_api.Request, *go_api.Response) error
	Login(context.Context, *go_api.Request, *go_api.Response) error
}

func RegisterGatewayHandler(s server.Server, hdlr GatewayHandler, opts ...server.HandlerOption) error {
	type gateway interface {
		Call(ctx context.Context, in *go_api.Request, out *go_api.Response) error
		Login(ctx context.Context, in *go_api.Request, out *go_api.Response) error
	}
	type Gateway struct {
		gateway
	}
	h := &gatewayHandler{hdlr}
	return s.Handle(s.NewHandler(&Gateway{h}, opts...))
}

type gatewayHandler struct {
	GatewayHandler
}

func (h *gatewayHandler) Call(ctx context.Context, in *go_api.Request, out *go_api.Response) error {
	return h.GatewayHandler.Call(ctx, in, out)
}

func (h *gatewayHandler) Login(ctx context.Context, in *go_api.Request, out *go_api.Response) error {
	return h.GatewayHandler.Login(ctx, in, out)
}
