version: '3'
services:
  api-gateway:
    build: ./api-gateway
    ports:
    - 50050:50050
    environment:
      MICRO_SERVER_ADDRESS: ":50050"
    depends_on:
      - consul
  greeter:
    build: ./service/greeter
    ports:
    - 50051:50051
    environment:
      MICRO_SERVER_ADDRESS: ":50051"
    depends_on:
    - consul
  user:
    build: ./service/user
    ports:
    - 50052:50052
    environment:
      MICRO_SERVER_ADDRESS: ":50052"
    depends_on:
      - consul
  consul:
    image: consul
    ports:
    - "8500:8500"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500"]
      interval: 5s
      timeout: 10s
      retries: 5